name: Deploy syncing-service
on:
  push:
    branches:
      - production
    paths:
      - 'syncingService/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      syncing-service: ${{ 'syncingService' }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Build and push image for chat service"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_PUSH_USERNAME }}
          password: ${{ secrets.ACR_PUSH_PASS }}
      - run: |
          cd ${{env.syncing-service}}
          echo "Building image for chat service"

